#!/usr/bin/env bash

# Load SkyBase environment variables into the current shell:
#   source ./scripts/env.sh
#
# Override any value before sourcing if needed:
#   SKYBASE_HTTP_ADDR=":9090" source ./scripts/env.sh

export SKYBASE_APP_NAME="${SKYBASE_APP_NAME:-SkyBase}"
export SKYBASE_ENV="${SKYBASE_ENV:-dev}"

export SKYBASE_HTTP_ADDR="${SKYBASE_HTTP_ADDR:-:8080}"

export SKYBASE_ADMIN_USERNAME="${SKYBASE_ADMIN_USERNAME:-admin}"
export SKYBASE_ADMIN_PASSWORD="${SKYBASE_ADMIN_PASSWORD:-admin123}"

export SKYBASE_REDIS_ADDR="${SKYBASE_REDIS_ADDR:-172.16.61.36:6613}"
export SKYBASE_REDIS_PASSWORD="${SKYBASE_REDIS_PASSWORD:-}"
export SKYBASE_REDIS_DB="${SKYBASE_REDIS_DB:-0}"
export SKYBASE_SESSION_TTL="${SKYBASE_SESSION_TTL:-12h}"

export SKYBASE_AGENT_VERSION="${SKYBASE_AGENT_VERSION:-}"
export SKYBASE_AGENT_DOWNLOAD_ID="${SKYBASE_AGENT_DOWNLOAD_ID:-latest}"
export SKYBASE_AGENT_DOWNLOAD_FILE="${SKYBASE_AGENT_DOWNLOAD_FILE:-}"

export SKYBASE_DB_HOST="${SKYBASE_DB_HOST:-172.16.61.36}"
export SKYBASE_DB_PORT="${SKYBASE_DB_PORT:-6612}"
export SKYBASE_DB_USER="${SKYBASE_DB_USER:-root}"
export SKYBASE_DB_PASSWORD="${SKYBASE_DB_PASSWORD:-emacle2013}"
export SKYBASE_DB_NAME="${SKYBASE_DB_NAME:-skyvv}"
